configured_endpoints: 36
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/val-town%2Fval-town-fb890bfd4bf755768d12bd8320dbba6da76e94677c21d52ddfbef8cb614f3bd7.yml
openapi_spec_hash: dea2c6cb81b52b242ac1e6a508f25439
config_hash: 4424cdfdf86a3bfc240eca8dcecd7499
